/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.dac.avaliacao.GUI;

import br.edu.ifpb.dac.avaliacao.daojpa.Dao;
import br.edu.ifpb.dac.avaliacao.daojpa.DaoFactory;
import br.edu.ifpb.dac.avaliacao.q6.entidades.Cliente;
import br.edu.ifpb.dac.avaliacao.q6.entidades.Conta;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author João Marcos F <joaomarccos.ads@gmail.com>
 */
public class OptionsPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private final boolean SUCESS = true;

    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    OptionsPanel(MainFrame mainFrame) {
        this();
        this.mainFrame = mainFrame;
        this.jLabelSaldo.setText("" + mainFrame.getLoggedUser().getConta().getSaldo());
        this.jPanelDisplay.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonSaque = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jPanelDisplay = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonConfirm = new javax.swing.JButton();
        jLabeloperationResult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonExtrato = new javax.swing.JButton();
        jButtonExcluirConta = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Banco DAC");

        jButtonEditar.setText("Editar Dados");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSaque.setText("Realizar um saque");
        jButtonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaqueActionPerformed(evt);
            }
        });

        jButtonDeposito.setText("Realizar um deposito");
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });

        jPanelDisplay.setBackground(new java.awt.Color(241, 234, 234));
        jPanelDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        jPanelDisplay.setEnabled(false);

        jLabel2.setText("Valor:");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jButtonConfirm.setText("Confirmar");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jLabeloperationResult.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabeloperationResult.setForeground(new java.awt.Color(19, 162, 35));
        jLabeloperationResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeloperationResult.setText("  ");

        javax.swing.GroupLayout jPanelDisplayLayout = new javax.swing.GroupLayout(jPanelDisplay);
        jPanelDisplay.setLayout(jPanelDisplayLayout);
        jPanelDisplayLayout.setHorizontalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisplayLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirm))
                    .addComponent(jLabeloperationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDisplayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDisplayLayout.setVerticalGroup(
            jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabeloperationResult)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Saldo atual da conta: ");

        jLabelSaldo.setText("Valor");

        jLabel4.setText("Operaçoes");

        jButtonExtrato.setText("Extrato da Conta");
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        jButtonExcluirConta.setText("Excluir conta");
        jButtonExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSaldo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonExcluirConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jLabel1)
                    .addComponent(jButtonEditar)
                    .addComponent(jLabel4))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExtrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluirConta))
                    .addComponent(jPanelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelSaldo))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.mainFrame.setLoggedUser(null);
        this.mainFrame.setContentPane(new LoginPanel(mainFrame));
        this.mainFrame.setVisible(true);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        this.mainFrame.setContentPane(new EditarDadosPanel(mainFrame));
        this.mainFrame.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaqueActionPerformed
        this.jPanelDisplay.setVisible(true);
        this.jLabeloperationResult.setText(" ");
        this.jButtonConfirm.setText("Sacar");
    }//GEN-LAST:event_jButtonSaqueActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        this.jPanelDisplay.setVisible(true);
        this.jLabeloperationResult.setText(" ");
        this.jButtonConfirm.setText("Depositar");
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        try {
            double valor = Double.parseDouble(jTextFieldValor.getText());
            if (jButtonConfirm.getText().equals("Sacar")) {
                sacar(valor);
            } else {
                depositar(valor);
            }
        } catch (NumberFormatException e) {
            jLabeloperationResult.setForeground(Color.RED);
            jLabeloperationResult.setText("Impossivel");
        }

    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void depositar(double valor) {
        boolean resultOperation = this.mainFrame.getLoggedUser().getConta().creditar(valor);
        if (resultOperation == SUCESS) {
            jLabeloperationResult.setForeground(Color.BLUE);
            jLabeloperationResult.setText("sucesso!");
            updateAccount();
        } else {
            jLabeloperationResult.setForeground(Color.RED);
            jLabeloperationResult.setText("Quantia invalida");
        }
    }

    private void updateAccount() {
        jTextFieldValor.setText("");
        Dao<Conta> daoConta = DaoFactory.createDaoJpa();
        daoConta.atualizar(this.mainFrame.getLoggedUser().getConta());
        Dao<Cliente> daoCliente = DaoFactory.createDaoJpa();        
        this.mainFrame.getLoggedUser().setConta(daoConta.buscar(this.mainFrame.getLoggedUser().getConta().getCodigo(), Conta.class));
        jLabelSaldo.setText(String.format("%.2f",this.mainFrame.getLoggedUser().getConta().getSaldo()));
    }

    private void sacar(double valor) {
        boolean operationResult;
        if (autenticar()) {
            operationResult = this.mainFrame.getLoggedUser().getConta().debitar(valor);
            if (operationResult == SUCESS) {
                jLabeloperationResult.setForeground(Color.BLUE);
                jLabeloperationResult.setText("sucesso!");
                updateAccount();
            } else {
                jLabeloperationResult.setForeground(Color.RED);
                jLabeloperationResult.setText("Quantia invalida");
            }
        } else {
            jLabeloperationResult.setForeground(Color.RED);
            jLabeloperationResult.setText("Senha invalida!");
        }

    }

    private boolean autenticar() {
        JLabel label = new JLabel("Senha:");
        JPasswordField jpf = new JPasswordField();
        JOptionPane.showConfirmDialog(this,
                new Object[]{label, jpf}, "Autenticaçao requerida:",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        return jpf.getText().equals(mainFrame.getLoggedUser().getConta().getSenha());

    }

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
        this.mainFrame.setContentPane(new ExtratoPanel(mainFrame));
        this.mainFrame.setVisible(true);
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    private void jButtonExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirContaActionPerformed
        int op = JOptionPane.showConfirmDialog(mainFrame, "Essa operaçao deixara voce liso! tem certeza?", "Exclusao de Conta", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(op == JOptionPane.OK_OPTION){
            Dao<Cliente> dao = DaoFactory.createDaoJpa();
            Cliente cli = dao.buscar(this.mainFrame.getLoggedUser().getLogin(), Cliente.class);
            dao.excluir(cli);
            this.mainFrame.setLoggedUser(null);
            this.mainFrame.setContentPane(new LoginPanel(mainFrame));
            this.mainFrame.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonExcluirContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluirConta;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabeloperationResult;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDisplay;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
